stages:
  prepare-s2orc:
    cmd: python scripts/s2orc/prepare_full_csv.py
    deps:
    - mars/s2orc/metadata/ai/
    - scripts/s2orc/prepare_full_csv.py
    outs:
    - data/s2orc/s2orc_ai_prefiltered.csv
  process-spacy-s2orc:
    cmd: python scripts/s2orc/process_spacy_docs.py #TODO: update this 
    deps:
    - data/s2orc/s2orc_ai_prefiltered.csv
    - scripts/s2orc/process_spacy_docs.py
    outs:
    - data/s2orc/s2orc_ai_prefiltered_processed_with_doi.pkl
  extract-phrases-s2orc:
    cmd: python scripts/s2orc/extract_phrases.py
    deps:
    - scripts/s2orc/extract_phrases.py
    - data/s2orc/s2orc_ai_prefiltered_processed_with_doi.pkl
    outs:
    - data/s2orc/extracted_phrases.csv

# big-ai-s2orc
  process-spacy-docs-big-s2orc:
    cmd: python scripts/s2orc/process_spacy_docs.py data/s2orc/big_ai_dataset.parquet data/s2orc/big_ai_spacy_docs.joblib --spacy-model-name en_core_web_md
    deps:
    - scripts/s2orc/process_spacy_docs.py
    - data/s2orc/big_ai_dataset.parquet
    outs:
    - data/s2orc/big_ai_spacy_docs.joblib

  process-spacy-sm-docs-big-s2orc:
    cmd: python scripts/s2orc/process_spacy_docs.py data/s2orc/big_ai_dataset.parquet data/s2orc/big_ai_spacy_docs.joblib --spacy-model-name en_core_web_sm
    deps:
    - scripts/s2orc/process_spacy_docs.py
    - data/s2orc/big_ai_dataset.parquet
    outs:
    - data/s2orc/big_ai_spacy_sm_docs.joblib

  extract-noun-chunks-big-s2orc:
    cmd: python scripts/s2orc/extract_phrases.py data/s2orc/big_ai_spacy_docs.joblib data/s2orc/big_ai_with_noun_chunks.parquet
    deps:
    - scripts/s2orc/extract_phrases.py
    - data/s2orc/big_ai_spacy_docs.joblib
    outs:
    - data/s2orc/big_ai_with_noun_chunks.parquet

  embedd-noun-chunks-big-s2orc:
    cmd: python 