AI_PAPER_PATTERNS = [
"Transfer Learning",
"Gradient Boosting",
"Adversarial Learning",
"Feature Learning",
"Generative Adversarial Net*",
"Representation Learning",
"(Multiagent Learning|Multi‑agent Learning)",
"Reservoir Computing",
"Co‑training",
"(Pac Learning|Probabl* Approximate* Correct Learning)",
"Extreme Learning Machine*",
"Ensemble Learning",
"Machine* Intelli‑gen*",
"(Neuro fuzzy|Neurofuzzy)",
"Lazy Learning",
"(Multi* instance Learning|Multi‑instance Learning)",
"(Multi* task Learning|Multitask Learning)",
"Computation* Intelligen*",
"Neural Model*",
"(Multi* label Learning|Multilabel Learning)",
"Similarity Learning",
"Statistical Relation* Learning",
"Support* Vector* Regression",
"Manifold Regulari?ation",
"Decision Forest*",
"Generali?ation Error*",
"Transductive Learning",
"(Neurorobotic*|Neuro‑robotic*)",
"Inductive Logic Programming",
"Natural Language Understanding",
"(Ada‑boost*|Adaptive Boosting)",
"Incremental Learning",
"Random Forest*",
"Metric Learning",
"Neural Gas",
"Grammatical Inference",
"Support* Vector* Machine*",
"(Multi* label Clas‑sification|Multilabel Classification)",
"Conditional Random Field*",
"(Multi* class Classifica‑tion|Multiclass Classification)",
"Mixture Of Expert*",
"Concept* Drift",
"Genetic Program‑ming",
"String Kernel*",
"(Learning To Rank*|Machine‑learned Ranking)",
"Boosting Algorithm$",
"Robot* Learning",
"Relevance Vector* Machine*",
"Connectionis*",
"(Multi* Kernel$ Learning|Multikernel$ Learning)",
"Graph Learning",
"Naive bayes* Classifi*",
"Rule‑based System$",
"Classification Algorithm*",
"Graph* Kernel*",
"Rule* induction",
"Manifold Learning",
"Label Propagation",
"Hypergraph* Learning",
"One class Classifi*",
"Intelligent Algorithm*"
]